name: dart_logging_abstraction
description: An logging abstraction package for logging, defines interfaces, common classes and default implementations.
version: 1.0.2
repository: https://github.com/codelovercc/dart_logging_abstraction

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
